Feature/27 Implement CRUD methods for Party table
olena-syrotenko/asd-java-intern pull request #29
Opened 2022-11-04 07:52 UTC by olena-syrotenko

2022-11-07 10:10 UTC, rdovgan requested changes

2022-11-07 11:54 UTC, olena-syrotenko commented on src/test/java/team/asd/service/PartyServiceTest.java
> +}
done

2022-11-07 11:59 UTC, olena-syrotenko commented on src/main/java/team/asd/service/PartyService.java
> +		if (id == null || id <= 0) {
done

2022-11-08 09:22 UTC, rdovgan approved these changes

2022-11-08 09:23 UTC, merged